version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore FoodTime\FoodTime.sln
image: Visual Studio 2017
build:
  verbosity: minimal
test:
  assemblies:
    only:
      - FoodTime.UnitTest.dll
# notifications:
#   - provider: Slack
#     auth_token:
#         secure: "Tf9aa4rBrKSe4VfgZbETWWXcuvWTxZkQbhlKuZ/LS0C66QnkrS7pe1Ohzk6J33xdbJVWPkZAM342Zd/Oc8oHVQ=="
#     channel: "food-time"