version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore FoodTime\FoodTime.sln
image: Visual Studio 2017
build:
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: tcc-foodtime
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false